version: '3'
services:
  db:
    image: postgres:10.5
    environment:
      POSTGRES_USER: tixdrop
      POSTGRES_PASSWORD: tixdrop
    volumes:
      - "/dbs/postgres-db/tixdrop:/var/lib/postgresql/data"
  web:
    build: .
    image: web:latest
    environment:
      DATABASE_URL: ecto://tixdrop:tixdrop@db/tix_prod
      PORT: 80 
      PGHOST: db 
      PGPORT: 5432
      PGUSER: tixdrop
    command: ./entrypoint.sh 
    ports:
      - "80:80"
    links:
      - db
